aws-load-balancer-operator: Remove AWS WAF Classic resources creation and deletion from ROSA install steps workflow
aws-load-balancer-operator e2e tests were failing permanently with
the following message on the attempt to create aws waf regional acl:
WAFBadRequestException: AWS WAF Classic (v1) support will end on September 30, 2025.
Effective May 1st, 2025, the creation of new WebACL v1 is no longer permitted.

Remove commands responsible for creating and deleting WAF Classic resources within
the pre-install and post-install steps of the ROSA install workflow.

* ci-operator/step-registry/aws-load-balancer/post-install-rosa/aws-load-balancer-post-install-rosa-commands.sh:
Remove post-install deletion of aws waf regional acl.
* ci-operator/step-registry/aws-load-balancer/pre-install-rosa/aws-load-balancer-pre-install-rosa-commands.sh:
Remove pre-install creation of aws waf regional acl.
Remove unused variables E2E_INPUT_WAF_WEBACL and E2E_WAF_WEB_ACL_NAME.
* ci-operator/config/openshift/aws-load-balancer-operator/openshift-aws-load-balancer-operator-main.yaml:
Remove unused variable ALBO_E2E_WAF_WEBACL_ID.
* ci-operator/config/openshift/aws-load-balancer-operator/openshift-aws-load-balancer-operator-release-1.0.yaml:
Remove unused variable ALBO_E2E_WAF_WEBACL_ID.
* ci-operator/config/openshift/aws-load-balancer-operator/openshift-aws-load-balancer-operator-release-1.1.yaml:
Remove unused variable ALBO_E2E_WAF_WEBACL_ID.